version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm[dev] :"
    groups:
      core:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/back_flask"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "pip[dev] :"
    groups:
      core:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
